markdown: kramdown

permalink: /:categories/:year-:month-:day-:title:output_ext

markdown: kramdown

kramdown:
  hard_wrap: true

# site data 
url: https://www.timculverhouse.com
title: CulverWeb
description: Tim Culverhouse's Website
author: 
  name: Tim Culverhouse

